fix(add): check if file exists before trying to move file
The functions get_absolute_path or mkdir does not complain if the file
doesn't exist, so the script reaches mv before failing. It is better
to check if the file exists before continuing.

diff --git a/dotig b/dotig
--- a/dotig
+++ b/dotig
@@ -732,6 +732,7 @@ add_dotfiles() {
   fi
 
   for _dotfile in "${_dotfiles[@]}"; do
+    [ ! -e "$_dotfile" ] && printf "%sError:%s %s is not a file.\n" "$_error_color" "$_no_color" "$_dotfile" && exit 2
     get_absolute_path _dotfile
     _dest="$DOTIG_PATH/home${_dotfile#$HOME}"
     if [ -f "$_dest" ]; then
